global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: private-lte-simulator
    metrics_path: /metrics
    static_configs:
      - targets:
          - simulator:8000
        labels:
          service: kpi-simulator
          network: private-lte
